### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/media_manager_autorewrite#1]
@schuer kannst das noch irgendwie in die Friendspage reinhauen? Ist neu das AddOn

**Comment by schuer** [comment]
Längst geschehen :)

**Comment by hirbod** [comment]
Superhero

**Comment by schuer** [comment]
Kannst du übrigens beim nächsten Mal auch selbst machen. Gibt eine `projects.yml`, in der alle drin stehen. Und mit jedem Push wird die Website automatisch gebaut (zusätzlich per Cron täglich gegen 12:15 Uhr).

**Comment by hirbod** [comment]
Alles klar, danke. Ich hab gerade versucht das bei Redaxo.org über den Installer hochzuladen, keine Ahnung wie das geht. Kannst du das erledigen? Wärst du noch mal bitte so ein Superhero? Danke!
