### ISSUE TITLE
Eigene Url

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/media_manager_autorewrite#11]
Ist es denkbar, eigene URLS für die Bilder vorzusehen? Ähnlich den URL Einstellungen der Artikel? Falls nicht wäre es eine Alternative die Bilder so aufzubauen: www.domain.de/image_mediatyp.jpg. So wären die Urls kürzer und schöner und die Bilder wären trotzdem sauber nach Medientyp benannt.

**Comment by hirbod** [comment]
Würde aber vermutlich das führen einer Pathlist bedeuten. Ich bin dagegen, da es Overhead ohne nennenswerten Vorteil bedeutet... ggf. wäre es mit einem RegExp htaccess entry möglich.. PR welcome, falls du eine Idee hast.

**Comment by hirbod** [comment]
Stale
