### ISSUE TITLE
images statt media in URL Pfad

### ISSUE THREAD

**Issue by ghost** [FriendsOfREDAXO/media_manager_autorewrite#14]
In yRewrite ist der rewrite über den Pfad mit **images** oder **imagetypes** als deprecated gekennzeichnet.

[Commit mit der Änderung an der .htaccess Datei](https://github.com/yakamara/redaxo_yrewrite/commit/6da5396244434e4ebefae883f86a3b7bcb5cea7e)

Sollte man die Ersetzung dann nicht auf **media** statt **images** verändern? 
Ich persönlich finde media auch schöner als images. Gibst Meinungen dazu?

_Edit: Link falsch gesetzt_

**Comment by hirbod** [comment]
Find ich prinzipiell in Ordnung, man müsste dann ggf. einen Versionscheck einbauen um zwischen den Versionen zu prüfen und dann eben /images/ oder /media/ auszugeben. Bedeutet gleich wieder "replace overhead". 

Wir könnten eine neue Version releasen, welche 2.3 vom yRewrite zur Voraussetzung macht.

**Comment by ghost** [comment]
Ich denke, dass man die yRewrite Version anheben sollte und es dann auf **media** ändert.

**Comment by hirbod** [comment]
Fixed
