### ISSUE TITLE
Release schnüren und in den Installer stellen

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/media_manager_autorewrite#21]
v 1.1.1 schnüren.

BC erwähnen, da das update alle rewrites von images/ auf media/ ändert.
Es betrifft hier eig. nur SEO, die Bilder bleiben weiter aufrufbar. 

@skerbis vllt machst du das ja 👍 
:-*

**Comment by skerbis** [comment]
Ja. Aber lass mich mal weiter gucken. Vielleicht finde ich noch was.

**Comment by hirbod** [comment]
Ja in der Readme steht noch Images

**Comment by skerbis** [comment]
hmm ... oder ein Setting anbieten und die Leute selbst entscheiden lassen?
- So könnte man bei einem Update bei images bleiben und bei einer frischen Install direkt media anbieten?

**Comment by hirbod** [comment]
Normalerweise würde ich sagen, keine Setting, weils einfach nur "bloated", da dieses AddOn aber bereits eine Settingspage hat, könnte man das machen

**Comment by skerbis** [comment]
Ich mach's dann so. Dann müssen wir's auch nicht 2.0 nennen ;-)

**Comment by skerbis** [comment]
Ich habe noch mal drüber nachgedacht. Kein Setting. Ist irgendwie sinnlos. Wer die alte Schreibweise will soll das alter Release vor 2.0 nehmen - Ich mach dann mal das Release
