### ISSUE TITLE
Update auf v2.0.0 macht Artikel in Kategorie 'Media' unerreichbar

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/media_manager_autorewrite#22]
Hej,
das Update auf v2.0.0 macht Artikel in der Kategorie 'Media' unerreichbar; z.B. liefert ein Artikel `/media/downloads.html` einen Fehler 404. Wir nutzen die Kategorie sehr intensiv, schon aus Redaxo-Urzeiten, als die Bilder noch im `/images` Verzeichnis lagen. Bisher gab es bei der Koexistenz von Artikeln und Medienpool im Verzeichnis `/media` keine Probleme.

Ich hätte gerne einen PR angeboten, kann die .htaccess aber leider nicht finden. Darum hier mein Änderungsvorschlag:

```htaccess
RewriteCond %{REQUEST_URI} !\.(htm|html)$
RewriteRule ^media/([^/]+)/(.*) %{ENV:BASE}/index.php?rex_media_type=$1&rex_media_file=$2&%{QUERY_STRING} [B]
RewriteCond %{REQUEST_URI} !\.(htm|html)$
RewriteRule ^media/(.*) %{ENV:BASE}/index.php?rex_media_type=default&rex_media_file=$1&%{QUERY_STRING} [B]
```

Neu sind die beiden `RewriteCond` Zeilen. Dadurch wird alles außer .htm(l) Dateien umgeschrieben.

Ich hoffe ihr berücksichtigt meine Ergänzung.

Vielen Dank und Liebe Grüße
Oliver

**Comment by hirbod** [comment]
@omphteliba das AddOn liefert keine .htaccess mit, da wir auf yRewrites Default-Einträge zurückgreifen. Das AddOn macht nur die URLs hübsch, nichts weiter. Wir haben lediglich mit der Version 2 die Pfade angepasst.

yRewrite hat /images bereits lange deprecated, es ist also nur eine Frage der Zeit, bis die Fallback Einträge vollständig verschwinden.

Es gibt also nichts, was das AddOn hier für dich tun könnte. Du hast zum Glück ja eine Lösung für deinen Edge-Case via Custom htaccess Regeln gefunden.
