### ISSUE TITLE
srctags unterstützen

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/media_manager_autorewrite#3]
oder sollte das lieber das media_manager_srctags addon plugin machen?

**Comment by hirbod** [comment]
Nimmt man diesen Kommentar an https://github.com/redaxo/redaxo/issues/1030#issuecomment-279305723, könnte man generell den Image Manager string replacen. Ich weiss nur nicht, ob man das in dieser Form möchte. Außerdem ist @phoebusryan Art auf die strikte Reihenfolge beschränkt.

Nur in selbst definierten attributen replacen, oder hart alles?

**Comment by hirbod** [comment]
nach weiterem bequatschen im slack -> closed. Es gibt jetzt dafür eine method.

**Comment by phoebusryan** [comment]
nämlich?

**Comment by hirbod** [comment]
siehe readme
