### ISSUE TITLE
Unterverzeichnis?

### ISSUE THREAD

**Issue by Poper123** [FriendsOfREDAXO/media_manager_autorewrite#9]
Wenn Redaxo in einem Unterverzeichnis installiert wird, funktionieren die Links nicht.

**Comment by hirbod** [comment]
Das musst du dann vermutlich über die htaccess steuern.

**Comment by Poper123** [comment]
Bei den den Links im Frontend fehlt der Unterpfad. Habe dazu in der boot.php den Pfad eingetragen;
            
$path = ($baseTag === true) ? '' : '/Unterordner/';

**Comment by hirbod** [comment]
Ok, danke für die Rückmeldung. Also brauchen wir eigentlich noch in den Einstellungen ein Feld für "Unterverzeichnis", damit das per Config gesteuert werden kann. Schiebe ich demnächst nach.

**Comment by hirbod** [comment]
Stale.
